workflows:
  ios-testflight:
    name: iOS TestFlight
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.wenchaoliu.test
      vars:
        XCODE_PROJECT: "test.xcodeproj"
        XCODE_SCHEME: "test"
        BUNDLE_ID: "com.wenchaoliu.test"
      xcode: latest
      cocoapods: default

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: master
          include: true

    scripts:
      - name: Set build number
        script: |
          agvtool new-version -all $(($(app-store-connect get-latest-testflight-build-number "$BUNDLE_ID") + 1))

      - name: Build ipa for distribution
        script: |
          xcode-project build-ipa \
            --project "$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME"

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
        beta_groups:
          - "Internal Testers"
      email:
        recipients:
          - haisky@live.com
        notify:
          success: true
          failure: true