name: iOS starter workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build and Test
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install certificate
        run: |
          CERT_PATH=$RUNNER_TEMP/cert.p12
          KEYCHAIN_PATH=$RUNNER_TEMP/build.keychain
          echo "${{ secrets.CERTIFICATES_P12 }}" | base64 --decode -o $CERT_PATH
          security create-keychain -p "temp123" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "temp123" $KEYCHAIN_PATH
          security import $CERT_PATH -P "${{ secrets.CERTIFICATES_P12_PASSWORD }}" \
            -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH

      - name: Install provisioning profile
        run: |
          PP_PATH=$RUNNER_TEMP/profile.mobileprovision
          echo "${{ secrets.PROVISIONING_PROFILE_BASE64 }}" | base64 --decode -o $PP_PATH
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles/dd3688d7-0425-4667-a40b-b1c651e6a72a.mobileprovision

      - name: Build
        run: |
          xcodebuild build \
            -project test/test.xcodeproj \
            -scheme test \
            -destination "generic/platform=iOS" \
            SWIFT_STRICT_CONCURRENCY=minimal \
            OTHER_SWIFT_FLAGS="-strict-concurrency=minimal" \
            CODE_SIGNING_ALLOWED=YES
