name: iOS starter workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build and Test
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: |
          xcodebuild build-for-testing \
            -project test/test.xcodeproj \
            -scheme test \
            -destination "platform=iOS Simulator,name=iPhone 16" \
            SWIFT_STRICT_CONCURRENCY=minimal \
            OTHER_SWIFT_FLAGS="-strict-concurrency=minimal"

      - name: Test
        run: |
          xcodebuild test-without-building \
            -project test/test.xcodeproj \
            -scheme test \
            -destination "platform=iOS Simulator,name=iPhone 16"
